/**
 * RandomNumberGenerator.hpp
 * @author Alan José <alanjsdelima@gmail.com>
 *
 * The number randomization machine returns a random double generated by a uniform
 * real distribution using the Mersenne Twister engine. The mersenne twister engine
 * is a general-purpose pseudorandom number generator (PRNG).
 * Reference: M. Matsumoto and T. Nishimura, Mersenne Twister: A 623-Dimensionally
 * Equidistributed Uniform Pseudo-Random Number Generator, ACM Transactions
 * on Modeling and Computer Simulation, Vol. 8, No. 1, January 1998, pp 3-30.
 * Soruce: https://dl.acm.org/doi/abs/10.1145/272991.272995
 */

#ifndef RANDOM_NUMBER_GENERATOR_H
#define RANDOM_NUMBER_GENERATOR_H

#include <random>
#include <chrono>
#include <functional>

namespace rng
{

    class RandomNumberGenerator
    {

        private:
        
            std::mt19937 generator;

            std::uniform_real_distribution<> distribution;

            std::mt19937 &get_generator();

        public:

            RandomNumberGenerator(double min_value, double max_value, unsigned int seed);

            explicit RandomNumberGenerator(unsigned int seed);

            RandomNumberGenerator();

            double get_random_number();

            double get_random_number(double min_value, double max_value);
    };

};

#endif // RANDOM_NUMBER_GENERATOR_H